server:
  port: 8080
  servlet:
    contextPath: /graphql-book
    context-path: /graphql-book
spring:
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        maxLifetime: 180000
graphql:
  servlet:
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
    mapping: /graphql-book
  tools:
    schema-location-pattern: "**/*.graphqls"
        # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
        # specification and expectations of most clients, so use this option with caution
    introspection-enabled: true
graphiql:
  mapping: /graphiql-book
  endpoint: /graphql-book
